.class public abstract LT6/a$a;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = LT6/a;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "a"
.end annotation


# direct methods
.method public static a(LT6/a;I)[Ljava/lang/Object;
    .locals 0

    new-instance p0, Lk6/t;

    const-string p1, "Generated by Android Extensions automatically"

    invoke-direct {p0, p1}, Lk6/t;-><init>(Ljava/lang/String;)V

    throw p0
.end method
